token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzA4LCJpZGVuIjoiNDA4MzA4OTY3NTAxMDcwMzQ3IiwibWQiOnsidXNlcm5hbWUiOiJhcnV0c3VkYXIiLCJrZXlWZXJzaW9uIjozLCJkaXNjcmltaW5hdG9yIjoiMzcwNyJ9LCJ0cyI6MTUzODkzNjczODQ1MX0.a5iZ57XMxSMoq16pNW8Zyk9i_QwmUdHc4vE9NkL5NIQ"

cardNamesList = [
'Archers',
'Arrows',
'Baby Dragon',
'Balloon',
'Bandit',
'Barbarian Barrel',
'Barbarian Hut',
'Barbarians',
'Bats',
'Battle Ram',
'Bomb Tower',
'Bomber',
'Bowler',
'Cannon',
'Cannon Cart',
'Clone',
'Dark Prince',
'Dart Goblin',
'Electro Wizard',
'Elite Barbarians',
'Elixir Collector',
'Executioner',
'Fire Spirits',
'Fireball',
'Flying Machine',
'Freeze',
'Furnace',
'Giant',
'Giant Skeleton',
'Giant Snowball',
'Goblin Barrel',
'Goblin Gang',
'Goblin Giant',
'Goblin Hut',
'Goblins',
'Golem',
'Graveyard',
'Guards',
'Heal',
'Hog Rider',
'Hunter',
'Ice Golem',
'Ice Spirit',
'Ice Wizard',
'Inferno Dragon',
'Inferno Tower',
'Knight',
'Lava Hound',
'Lightning',
'Lumberjack',
'Magic Archer',
'Mega Knight',
'Mega Minion',
'Miner',
'Mini P.E.K.K.A',
'Minion Horde',
'Minions',
'Mirror',
'Mortar',
'Musketeer',
'Night Witch',
'P.E.K.K.A',
'Poison',
'Prince',
'Princess',
'Rage',
'Rascals',
'Rocket',
'Royal Ghost',
'Royal Giant',
'Royal Hogs',
'Royal Recruits',
'Skeleton Army',
'Skeleton Barrel',
'Skeletons',
'Sparky',
'Spear Goblins',
'Tesla',
'The Log',
'Three Musketeers',
'Tombstone',
'Tornado',
'Valkyrie',
'Witch',
'Wizard',
'X-Bow',
'Zap',
'Zappies'
]